name: Update ChinaMax rules

on:
  schedule:
    - cron: "0 19 * * *"
  workflow_dispatch:

jobs:
  update-chinamax-rules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run china_max_rule.py
      run: |
        python china_max_rule.py

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "53632549+uxudjs@users.noreply.github.com"
        git config --local user.name "uxudjs"
        git add china_max_sr.list README.md
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto update ChinaMax rules"
          git push origin HEAD:main --force
        fi
